// Package messages ports the static course-message catalog served by
// /messages/get-all-messages (admin-only).
//
// This package defines the Message type and the repository surface. The actual
// catalog data (the ~68 entries in the legacy photato-messages.js) is ported
// separately in phase 3b; NewRepository returns an unimplemented repository
// until then.
package messages

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// catalogJSON is the course-message catalog, ported verbatim from the legacy
// backend/messages/photato-messages.js (68 entries). It is regenerated by
// requiring the legacy module and dumping JSON, so the Hungarian UTF-8 content
// is preserved byte-for-byte rather than hand-retyped.
//
//go:embed photato-messages.json
var catalogJSON []byte

// Message is one entry in the course-message catalog. JSON field names mirror
// the legacy photato-messages.js objects, which the admin frontend consumes
// verbatim.
type Message struct {
	Slug           string `json:"slug"`
	Title          string `json:"title"`
	CourseDayIndex int    `json:"courseDayIndex"`
	Channel        string `json:"channel"`
	Audience       string `json:"audience"`
	Locale         string `json:"locale"`
	Subject        string `json:"subject,omitempty"`
	ContentType    string `json:"contentType"`
	Content        string `json:"content"`
}

// Repository serves the message catalog.
type Repository struct {
	catalog []Message
}

// NewRepository builds the catalog repository, decoding the embedded catalog.
// A malformed embed is a programming error (the data ships with the binary), so
// it panics rather than deferring the failure to request time.
func NewRepository() *Repository {
	var catalog []Message
	if err := json.Unmarshal(catalogJSON, &catalog); err != nil {
		panic(fmt.Sprintf("messages: decoding embedded catalog: %v", err))
	}
	return &Repository{catalog: catalog}
}

// GetAll returns the full message catalog.
func (r *Repository) GetAll() ([]Message, error) {
	return r.catalog, nil
}
